### PR TITLE
Fix problem of undici with not nodejs platforms (PART 1)

### PR DESCRIPTION
**Pull request by vladmitchenko**

### CODE REVIEW

**Review by vitalyrudenko-affinidi — APPROVED** [review]

**Review by inga-affinidi — CHANGES_REQUESTED** [review]
This will be fixed as a part of https://lemmatree.atlassian.net/browse/FTL-2702 ; and this PR does not solve a problem with webpack trying to require `undici` anyway.

**Comment by vitalyrudenko-affinidi** [comment]
@inga-affinidi it should. If package is not install, webpack will show a warning - yet will build the project anyway.

**Comment by anton-iskryzhytskyi** [comment]
@vladmitchenko let's close it for now, as we decided to use @inga-affinidi approach

**Comment by inga-affinidi** [comment]
This is solved by #198

**Pull request closed without merging**
